import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Shared/Navbar/Navbar";
import { poppins } from "./fonts/Fonts";
import Footer from "./Shared/footer/Footer";
import TopButton from "./Shared/Button/TopButton";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"], // required
  weight: ["400", "600", "700"], // optional: choose the weights you need
  display: "swap", // prevents FOIT (flash of invisible text)
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="overflow-x-hidden" id="root-layout">
          <Navbar />
          {children}
          <TopButton />
          <Footer />
        </div>
      </body>
    </html>
  );
}
